name = "Create Aero"
author = "Max"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "302046007af69037588c91fc087ee9ffbbed756ec3c4dac863d2db5c7ad8aedc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
