name = "Create Aero"
author = "Max"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b602aad3028b027299763973107883be1487d19f16772eaecb9786ef36d6a44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
