name = "Create Aero"
author = "Max"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27092605ad987a8ffbcd20c07433a6cc1c68d9d4be710b961b7e9f51bac22a6d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
